# Generated by Django 5.0.6 on 2024-07-27 05:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_year_course_semester_remove_course_idteacher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGradesStudent',
            fields=[
                ('idCourseGradesStudent', models.AutoField(primary_key=True, serialize=False)),
                ('finalGrade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('idCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('idStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
                ('id_user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_created_grades_students', to=settings.AUTH_USER_MODEL)),
                ('id_user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_modified_grades_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
